[theme]
primaryColor = "#004080"  # Warna tombol dan elemen utama
backgroundColor = "#ADD8E6"  # Warna latar belakang (biru muda)
secondaryBackgroundColor = "#FFFFFF"  # Warna latar belakang kedua
textColor = "#000000"  # Warna teks
font = "sans serif"  # Jenis font (opsional)
